/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as OgImageRouteImport } from './routes/og-image'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'
import { Route as ProjectsChar123SlugChar125RouteImport } from './routes/projects/{-$slug}'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const OgImageRoute = OgImageRouteImport.update({
  id: '/og-image',
  path: '/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsChar123SlugChar125Route =
  ProjectsChar123SlugChar125RouteImport.update({
    id: '/projects/{-$slug}',
    path: '/projects/{-$slug}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/og-image': typeof OgImageRoute
  '/terminal': typeof TerminalRoute
  '/projects/{-$slug}': typeof ProjectsChar123SlugChar125Route
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/og-image': typeof OgImageRoute
  '/terminal': typeof TerminalRoute
  '/projects/{-$slug}': typeof ProjectsChar123SlugChar125Route
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/og-image': typeof OgImageRoute
  '/terminal': typeof TerminalRoute
  '/projects/{-$slug}': typeof ProjectsChar123SlugChar125Route
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/og-image'
    | '/terminal'
    | '/projects/{-$slug}'
    | '/work/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/og-image' | '/terminal' | '/projects/{-$slug}' | '/work/$slug'
  id:
    | '__root__'
    | '/'
    | '/og-image'
    | '/terminal'
    | '/projects/{-$slug}'
    | '/work/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OgImageRoute: typeof OgImageRoute
  TerminalRoute: typeof TerminalRoute
  ProjectsChar123SlugChar125Route: typeof ProjectsChar123SlugChar125Route
  WorkSlugRoute: typeof WorkSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-image': {
      id: '/og-image'
      path: '/og-image'
      fullPath: '/og-image'
      preLoaderRoute: typeof OgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/{-$slug}': {
      id: '/projects/{-$slug}'
      path: '/projects/{-$slug}'
      fullPath: '/projects/{-$slug}'
      preLoaderRoute: typeof ProjectsChar123SlugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OgImageRoute: OgImageRoute,
  TerminalRoute: TerminalRoute,
  ProjectsChar123SlugChar125Route: ProjectsChar123SlugChar125Route,
  WorkSlugRoute: WorkSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
